server.port=8085
spring.application.name=ledger-service
spring.kafka.bootstrap-servers=localhost:9092
spring.datasource.url=jdbc:postgresql://localhost:5432/stockholm
spring.datasource.username=postgres
spring.datasource.password=postgres
management.endpoints.web.exposure.include=health,info,metrics

