server.port=8085
spring.application.name=ledger-service
spring.kafka.bootstrap-servers=localhost:9092
spring.datasource.url=jdbc:postgresql://localhost:5432/stockholm
spring.datasource.username=postgres
spring.datasource.password=postgres
management.endpoints.web.exposure.include=health,info,metrics

# Kafka topic config
stockholm.kafka.create-topics=true
stockholm.kafka.topics.settlement-completed=settlement.completed
stockholm.kafka.topics.ledger-updated=ledger.updated
stockholm.kafka.topics.ledger-failed=ledger.failed

spring.kafka.consumer.group-id=ledger-service-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.com.europe.sepa.ledger=DEBUG

