server.port=8089
spring.application.name=backoffice-api

spring.datasource.url=jdbc:postgresql://localhost:5432/stockholm
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

management.endpoints.web.exposure.include=health,info,metrics

